#!/bin/bash

# Useful variables
DATE=`date --iso -u`
REALDATE=`date --iso=seconds`
NIGHTLY=`pwd`
OUT=`pwd`/out
PDC_INC=`pwd`/PDCurses/
PDC_LIB=`pwd`/PDCurses/win32/pdcurses.a

rm -rf $OUT b
mkdir -p $OUT b

echo Builds started at `date --iso=seconds`.

# Update SVN or check out, depending
if test -d trunk ; then
	cd trunk && svn update
	if test $? -ne 0 ; then
	  exit 1
	fi
	cd ..
else
	svn checkout http://dev.rephial.org/svn/trunk/
	if test $? -ne 0 ; then
	  exit 1
	fi
fi

# Obtain revision
cd trunk &&
	REVISION=`svn info | grep ^Revision: | cut -d' ' -f2` &&
	cd ..

# Avoid needless compiles
if test -f oldrev; then
	# Compare new with old, and if they are the same, exit painlessly
	echo $REVISION | cmp oldrev && echo "Nothing to do." && exit 0 
fi

# Save old revision
echo $REVISION>oldrev


# Copy
cp -r trunk b/native &&
  cp -r trunk b/console &&
  cp -r trunk b/linux

# Windows native build
cd $NIGHTLY/b/native &&
  make -C src -f Makefile.win CROSS="ccache i586-mingw32msvc-" MINGW=yes \
    BUILD_ID=\\\"r$REVISION\\\" &&
  scripts/pkg_win angband-r$REVISION $OUT/angband-r$REVISION.zip &&
  echo "Windows build success."

# Windows console build
cd $NIGHTLY/b/console &&
  make -C src -f Makefile.win CROSS="ccache i586-mingw32msvc-" CONSOLE=yes \
    PDCURSES_INC=$PDC_INC PDCURSES_LIB=$PDC_LIB MINGW=yes \
    BUILD_ID=\\\"r$REVISION\\\" &&
  scripts/pkg_win angband-r$REVISION-con $OUT/angband-r$REVISION-con.zip &&
  echo "Windows console build success."

# Linux native build (ncurses)
#cd $NIGHTLY/b/linux &&
#  ./autogen.sh &&
#  ./configure --with-private-dirs &&
#  make &&
#  echo "Linux native build success."

# End
cd $NIGHTLY &&
  rm -rf b

echo Builds finished at `date --iso=seconds`.
